### ISSUE TITLE
undefined method issue

### ISSUE THREAD

**Issue by dnldp55** [ruby/did_you_mean#157] opened 2021-07-28 08:13 UTC
#redis-stat 

undefined method `display_width' for "┌────────────────────────":String
Did you mean?  display

how fix that?

redis - 3.2.12
gem - 3.2.22
ruby - 3.0.2 
centos 7

/usr/local/rvm/gems/ruby-3.0.2/gems/tabularize-0.2.10/lib/tabularize.rb:195:in `cell_width': undefined method `display_width' for "┌────────────────────────":String (NoMethodError)
Did you mean?  display
        from /usr/local/rvm/gems/ruby-3.0.2/gems/tabularize-0.2.10/lib/tabularize.rb:130:in `block (2 levels) in to_s'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/tabularize-0.2.10/lib/tabularize.rb:125:in `each'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/tabularize-0.2.10/lib/tabularize.rb:125:in `each_with_index'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/tabularize-0.2.10/lib/tabularize.rb:125:in `block in to_s'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/tabularize-0.2.10/lib/tabularize.rb:124:in `map'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/tabularize-0.2.10/lib/tabularize.rb:124:in `to_s'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/redis-stat-0.4.14/lib/redis-stat.rb:387:in `puts'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/redis-stat-0.4.14/lib/redis-stat.rb:387:in `output_static_info'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/redis-stat-0.4.14/lib/redis-stat.rb:129:in `block in start'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/lps-0.2.1/lib/lps.rb:38:in `loop'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/option_initializer-1.5.1/lib/option_initializer.rb:96:in `method_missing'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/redis-stat-0.4.14/lib/redis-stat.rb:110:in `start'
        from /usr/local/rvm/gems/ruby-3.0.2/gems/redis-stat-0.4.14/bin/redis-stat:13:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-3.0.2/bin/redis-stat:23:in `load'
        from /usr/local/rvm/gems/ruby-3.0.2/bin/redis-stat:23:in `<main>'

**Comment by olleolleolle** [comment] 2021-07-28 09:09
@dnldp55 Hello!

First off, this is not a defect in the did_you_mean library.

The issue is probably in `tabularize`, or redis-stat? 

> https://github.com/junegunn/tabularize

Hope this helps, and I'll close this report now. 👋

**Closed by olleolleolle** 2021-07-28 09:09 UTC
